---
- name: deploy to tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy to tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/webd/target/webd.war"
        dest: "/opt/tomcat/webapps/webd.war"
        remote_src: no

    - name: restart tomcat
      systemd:
        name: tomcat
        state: restarted

